apiVersion: v1alpha1
kind: AgentConfig
metadata:
  name: g8
rendezvousIP: 192.168.8.201
additionalNTPSources:
  - 192.168.8.1
hosts:
  - hostname: control0.g8.lo
    role: master
    interfaces:
      - name: enp6s18
        macAddress: 00:50:56:1f:26:26
  - hostname: control1.g8.lo
    role: master
    interfaces:
      - name: enp6s18
        macAddress: 00:50:56:1f:27:27
  - hostname: control2.g8.lo
    role: master
    interfaces:
      - name: enp6s18
        macAddress: 00:50:56:1f:28:28
  - hostname: worker0.g8.lo
    role: worker
    interfaces:
      - name: enp6s18
        macAddress: 00:50:56:1f:30:30
  - hostname: worker1.g8.lo
    role: worker
    interfaces:
      - name: enp6s18
        macAddress: 00:50:56:1f:31:31
  - hostname: worker2.g8.lo
    role: worker
    interfaces:
      - name: enp6s18
        macAddress: 00:50:56:1f:32:32
